// 4. Do code review of the code generated by Add OpenAccess Service wizard for Web API services
// Make critical code review (peer review) of the code generated by Add OpenAccess Service wizard 
// for Web API services: Base controller, Concrete controllers, Base repository, Concrete repositories, 
// Global asax routes definition
// Watch for bad practices in handling data-related task, bad design decisions, incorrect 
// implementation of design patterns, code smells, bad code formatting, inefficient code and etc. 
// List at least 3 issues with the generated code.

using System;

class CodeReviewUI
{
    static void Main()
    {
        Console.WriteLine(
            @"Task 4:
1. Violation of best practices - OpenAccessContext instances are not disposed explicitly
2.Inefficient code - OpenAccessBaseRepository.GetAll() – the fetch strategy is not used when loading the data, but only when detaching it.
3.Bad isolation of components – EntitiesModel implements IUnitOfWork which should be used instead of the real context type. 
Additionally the code will work fine with just targeting OpenAccessContext (the base class of EntitiesModel)");
    }
}
