#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TelerikAcademy.Data;

namespace TelerikAcademy.Data	
{
	public partial class Department
	{
		private int _departmentID;
		public virtual int DepartmentID
		{
			get
			{
				return this._departmentID;
			}
			set
			{
				this._departmentID = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private int _managerID;
		public virtual int ManagerID
		{
			get
			{
				return this._managerID;
			}
			set
			{
				this._managerID = value;
			}
		}
		
		private Employee _employee;
		public virtual Employee Employee
		{
			get
			{
				return this._employee;
			}
			set
			{
				this._employee = value;
			}
		}
		
		private IList<Employee> _employees = new List<Employee>();
		public virtual IList<Employee> Employees
		{
			get
			{
				return this._employees;
			}
		}
		
	}
}
#pragma warning restore 1591
