#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TelerikAcademy.Data;

namespace TelerikAcademy.Data	
{
	public partial class Employee
	{
		private int _employeeID;
		public virtual int EmployeeID
		{
			get
			{
				return this._employeeID;
			}
			set
			{
				this._employeeID = value;
			}
		}
		
		private string _firstName;
		public virtual string FirstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				this._firstName = value;
			}
		}
		
		private string _lastName;
		public virtual string LastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				this._lastName = value;
			}
		}
		
		private string _middleName;
		public virtual string MiddleName
		{
			get
			{
				return this._middleName;
			}
			set
			{
				this._middleName = value;
			}
		}
		
		private string _jobTitle;
		public virtual string JobTitle
		{
			get
			{
				return this._jobTitle;
			}
			set
			{
				this._jobTitle = value;
			}
		}
		
		private int _departmentID;
		public virtual int DepartmentID
		{
			get
			{
				return this._departmentID;
			}
			set
			{
				this._departmentID = value;
			}
		}
		
		private int? _managerID;
		public virtual int? ManagerID
		{
			get
			{
				return this._managerID;
			}
			set
			{
				this._managerID = value;
			}
		}
		
		private DateTime _hireDate;
		public virtual DateTime HireDate
		{
			get
			{
				return this._hireDate;
			}
			set
			{
				this._hireDate = value;
			}
		}
		
		private decimal _salary;
		public virtual decimal Salary
		{
			get
			{
				return this._salary;
			}
			set
			{
				this._salary = value;
			}
		}
		
		private int? _addressID;
		public virtual int? AddressID
		{
			get
			{
				return this._addressID;
			}
			set
			{
				this._addressID = value;
			}
		}
		
		private Address _address;
		public virtual Address Address
		{
			get
			{
				return this._address;
			}
			set
			{
				this._address = value;
			}
		}
		
		private Department _department;
		public virtual Department Department
		{
			get
			{
				return this._department;
			}
			set
			{
				this._department = value;
			}
		}
		
		private Employee _employee1;
		public virtual Employee Employee1
		{
			get
			{
				return this._employee1;
			}
			set
			{
				this._employee1 = value;
			}
		}
		
		private IList<Project> _projects = new List<Project>();
		public virtual IList<Project> Projects
		{
			get
			{
				return this._projects;
			}
		}
		
		private IList<Employee> _employees = new List<Employee>();
		public virtual IList<Employee> Employees
		{
			get
			{
				return this._employees;
			}
		}
		
		private IList<Department> _departments = new List<Department>();
		public virtual IList<Department> Departments
		{
			get
			{
				return this._departments;
			}
		}
		
	}
}
#pragma warning restore 1591
