//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IStringInAnotherApperancesService")]
public interface IStringInAnotherApperancesService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringInAnotherApperancesService/GetStringAppearancesInAnothe" +
        "rString", ReplyAction="http://tempuri.org/IStringInAnotherApperancesService/GetStringAppearancesInAnothe" +
        "rStringResponse")]
    int GetStringAppearancesInAnotherString(string originString, string testString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringInAnotherApperancesService/GetStringAppearancesInAnothe" +
        "rString", ReplyAction="http://tempuri.org/IStringInAnotherApperancesService/GetStringAppearancesInAnothe" +
        "rStringResponse")]
    System.Threading.Tasks.Task<int> GetStringAppearancesInAnotherStringAsync(string originString, string testString);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IStringInAnotherApperancesServiceChannel : IStringInAnotherApperancesService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class StringInAnotherApperancesServiceClient : System.ServiceModel.ClientBase<IStringInAnotherApperancesService>, IStringInAnotherApperancesService
{
    
    public StringInAnotherApperancesServiceClient()
    {
    }
    
    public StringInAnotherApperancesServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public StringInAnotherApperancesServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StringInAnotherApperancesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StringInAnotherApperancesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int GetStringAppearancesInAnotherString(string originString, string testString)
    {
        return base.Channel.GetStringAppearancesInAnotherString(originString, testString);
    }
    
    public System.Threading.Tasks.Task<int> GetStringAppearancesInAnotherStringAsync(string originString, string testString)
    {
        return base.Channel.GetStringAppearancesInAnotherStringAsync(originString, testString);
    }
}
