SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `booksystem` DEFAULT CHARACTER SET utf8 ;
USE `booksystem` ;

-- -----------------------------------------------------
-- Table `booksystem`.`books`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `booksystem`.`books` (
  `BookID` INT(11) NOT NULL AUTO_INCREMENT ,
  `Title` VARCHAR(45) NOT NULL ,
  `Author` VARCHAR(45) NOT NULL ,
  `PublishDate` DATE NULL DEFAULT NULL ,
  `ISBN` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`BookID`) ,
  UNIQUE INDEX `BookID_UNIQUE` (`BookID` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 70
DEFAULT CHARACTER SET = utf8;

USE `booksystem` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
