//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterLikeWebChat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageId { get; set; }
        public System.DateTime Date { get; set; }
        public string Content { get; set; }
        public int ChannelId { get; set; }
        public string AuthorId { get; set; }
    
        public virtual AspNetUser Author { get; set; }
        public virtual Channel Channel { get; set; }
    }
}
