//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket.Model.SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsTax
    {
        public long ID { get; set; }
        public string ProductName { get; set; }
        public decimal Tax { get; set; }
    }
}
